### ISSUE TITLE
Converting images to actual text

### ISSUE THREAD

**Issue by KrishMunot** [AlJohri/practice#1]
The readme contains images that are not very useful until they actually come "alive" and the links can be explored.

**Comment by AlJohri** [comment]
Any suggestions to be able to keep both? Perhaps a Makefile that compiles the READMEs into one? Would be one rather long README though.

**Comment by KrishMunot** [comment]
I don't see any reason why the images should even exist when the exact same textual version of the image is present.

**Comment by AlJohri** [comment]
PRs are welcome
